version: '2'
services:

### APACHE + PHP ###
    webserver:
      build: ./web
      container_name: php_7.1
      links:
        - dbserver
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./src:/var/www/html:cached 

### DB ###
    dbserver:
      build: ./db
      container_name: mysql_5.7
      ports: 
        - "3036:3036"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
      volumes_from:
        - data

### 保存領域 ###
    data:
      image: busybox
      container_name: data_container
